// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIikYiFsL_sYJGLduQGN_d8MwnE-N9jfU',
    appId: '1:204490633303:web:230b615b5d5bc437a8f312',
    messagingSenderId: '204490633303',
    projectId: 'collegeapp-cb9e0',
    authDomain: 'collegeapp-cb9e0.firebaseapp.com',
    storageBucket: 'collegeapp-cb9e0.appspot.com',
    measurementId: 'G-N8X0LCESSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0k18D3_tePV6pMWDGz2Ora-EQ_dFx3YI',
    appId: '1:204490633303:android:c7ac46cb132dcfd5a8f312',
    messagingSenderId: '204490633303',
    projectId: 'collegeapp-cb9e0',
    storageBucket: 'collegeapp-cb9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxKKx2U0B1BtYpDjfL6SNh_Qif1wCcn5A',
    appId: '1:204490633303:ios:2efa18d9a1c30d21a8f312',
    messagingSenderId: '204490633303',
    projectId: 'collegeapp-cb9e0',
    storageBucket: 'collegeapp-cb9e0.appspot.com',
    iosBundleId: 'com.college.collegeBanhaApp',
  );
}
